### ISSUE TITLE
Estructura de de los botes no contiene str

### ISSUE THREAD

**Issue by Axel2293** [Axel2293/Battleship#10]
Cambiar el char a str para tener el nombre completo

**Comment by Alv4rZ** [comment]
> Cambiar el char a str para tener el nombre completo

¿Los nombres completos serán en ingles? para ver de cuanto ponemos el tamaño del arreglo

**Comment by Axel2293** [comment]
Yo creo que en español, igualmente no se van a mostrar los nombres de cada bote registrado al usuario
